version: "3.8"
services:
  # rabbitmq:
  #   image: rabbitmq:3.8-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #       - 5673:5672
  #       - 15673:15672
  #   volumes:
  #       - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #       - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  #   networks:
  #       - rabbitmq_nodejs
  postgres:
    image: postgres:14
    container_name: postgres-seacows-backend
    ports:
      - "127.0.0.1:5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements", "-cmax_connections=200"]
    environment:
      POSTGRES_USER: seacows
      POSTGRES_PASSWORD: seacows
      POSTGRES_DB: seacows_backend
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    labels:
      logging: "promtail"

  redis:
    image: redis:6.2-alpine
    container_name: redis-seacows-backend
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - "/data/redis:/data"
    labels:
      logging: "promtail"

  seacows-backend:
    image: seacows-backend:dev
    container_name: seacows-backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: "development"
      DATABASE_URL: "postgresql://seacows:seacows@postgres:5432/seacows_backend?schema=public"
      DATABASE_WRITE_URL: "postgresql://seacows:seacows@postgres:5432/seacows_backend?schema=public"
      LOOKSRARE_API_KEY_1: "1313a13d1as3d13as1d"
      LOOKSRARE_API_KEY_2: "1313a13d1as3d13as1d"
      RESERVOIR_API_KEY_MAINNET_1: "611a8462-44e0-5c4b-acd8-3cab844f0220"
      RESERVOIR_API_KEY_GOERLI_1: "26ae7154-a498-5044-a963-b469fefdb223"
      RESERVOIR_API_KEY_SEPOLIA_1: "b8682e10-22f9-5dba-a00d-63a32ffb26e2"
      MORALIS_API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjM5N2RlMzQ2LWMxZTgtNGIyNS05Y2VhLTg0NzI2Y2Y3MGM2NyIsIm9yZ0lkIjoiMjUyMDAwIiwidXNlcklkIjoiMjU1NTY2IiwidHlwZUlkIjoiYmQxY2JiMDUtNjA1Ny00MzlmLTgwYTctNWNlNjliZTI4ODEyIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE2OTcyMDY2NDMsImV4cCI6NDg1Mjk2NjY0M30.OeNVG3NlYI01IyRx71nZWJPxEx7bdEWJy3hWupQ5QaM"
      CHAINS: "sepolia"
      CRON_PATTERN: "*/3 * * * * *"
      REDIS_URL: "redis://redis:6379/3"
      LOG_LEVEL: debug
    labels:
      logging: "promtail"
