version: "3.8"
services:
  # rabbitmq:
  #   image: rabbitmq:3.8-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #       - 5673:5672
  #       - 15673:15672
  #   volumes:
  #       - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #       - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  #   networks:
  #       - rabbitmq_nodejs
  postgres:
    image: postgres:14
    ports:
      - "127.0.0.1:5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements", "-cmax_connections=200"]
    environment:
      POSTGRES_USER: seacows
      POSTGRES_PASSWORD: seacows
      POSTGRES_DB: seacows_backend
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
